on:
  issues:
    types: [opened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Aveline-art/javascript-template-test@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          labelMap1: "size ~ size: missing"
          labelMap2: "Feature ~ Feature: missing"
          labelMap3: "role ~ role: missing"
